# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
sudo: false

language: node_js
node_js:
  - v5
  - v4

script: npm test && npm run-script report-coverage

notifications:
  email: false
